# RainbowNickname Configuration
#
# Animation speed in ticks (20 ticks = 1 second)
# Lower values = faster animation
# Recommended values: 2-8
animation-speed: 4

# Use bold text for nicknames
# true = bold nickname (&l)
# false = normal nickname
use-bold: true

# Smooth transition between colors
# true = smoother transition
# false = standard color change
smooth-transition: true

# Color configuration (for future versions)
# colors:
#   - DARK_RED
#   - RED
#   - GOLD
#   - YELLOW
#   - GREEN
#   - DARK_GREEN
#   - AQUA
#   - DARK_AQUA
#   - BLUE
#   - DARK_BLUE
#   - LIGHT_PURPLE
#   - DARK_PURPLE
