# RainbowNickname Plugin Configuration

# Rainbow animation speed (in ticks)
# 20 ticks = 1 second
# Lower values = faster animation
animation-speed: 10

# Use bold text for names
use-bold: true

# Nametag height above the player (in blocks)
# 2.3 is the standard height of a Minecraft nametag
nametag-height: 2.3
