# RainbowNickname Plugin Configuration - Optimized Version

# Rainbow animation speed (in ticks)
# 20 ticks = 1 second
# Lower values = faster animation, but more CPU usage
# Recommended: 5-10 for smooth animation
animation-speed: 5

# Use bold text for names
use-bold: true

# Nametag height above the player (in blocks)
# 2.3 is the standard height of a Minecraft nametag
nametag-height: 2.3

# Position update threshold (in blocks)
# Only update armor stand position if player moved more than this distance
# Lower values = smoother movement but more CPU usage
position-threshold: 0.1

# Use asynchronous tasks for heavy operations
# Improves performance by using separate threads
use-async-tasks: true

# Keep prefix and suffix from other plugins in tab list
# This will preserve ranks, titles, etc. from permission/chat plugins
# When true, FORCES tab names for ALL players to show their prefix/suffix
keep-prefix-suffix: true

# Animate prefix and suffix with rainbow effect too
# Only works if keep-prefix-suffix is true
# Warning: may cause visual clutter with long prefixes/suffixes
animate-prefix-suffix: false

# TPS Monitor Configuration
# Automatically adjusts animation speed when server TPS is low
tps-monitor:
  # Enable automatic speed adjustment based on TPS
  auto-adjust: true

  # Minimum TPS threshold - below this, animation will slow down
  min-tps: 19.0

  # Speed multiplier when lagging (0.5 = half speed)
  lag-speed-multiplier: 0.5

  # Maximum animation delay during lag (in ticks)
  # Prevents animation from becoming too slow
  max-lag-speed: 40

# LuckPerms compatibility settings
luckperms:
  # Delay before reading prefix/suffix after player join (in ticks)
  # Increase if LuckPerms prefixes don't show up
  # 20 ticks = 1 second, 40 = 2 seconds, 60 = 3 seconds
  join-delay: 60

  # Read prefix/suffix from player list name
  # Enable this for better LuckPerms compatibility
  read-from-tab: true

# Tab list configuration
tab-list:
  # Enable rainbow effect on tab list header and footer
  enabled: true

  # Tab list header (supports color codes with &)
  # Leave empty to disable header
  header: "&lRainbow Server"

  # Tab list footer (supports color codes with &)
  # Leave empty to disable footer
  footer: "&7Powered by RainbowNickname"

# Cache configuration
cache:
  # Maximum number of player names to cache
  # Each cached name uses ~1KB of memory
  max-size: 1000

# Performance tuning (Advanced users only)
performance:
  # Batch size for bulk operations
  batch-size: 50

  # Enable debug logging
  debug: false