# RainbowNickname Plugin Configuration

# Velocità dell'animazione arcobaleno (in ticks)
# 20 ticks = 1 secondo
# Valori più bassi = animazione più veloce
animation-speed: 10

# Usa il testo in grassetto per i nomi
use-bold: true

# Altezza della nametag sopra il giocatore (in blocchi)
# 2.3 è l'altezza standard della nametag di Minecraft
nametag-height: 2.3

# Messaggio di benvenuto (opzionale)
welcome-message: "&aIl tuo nickname è ora arcobaleno!"