name: RainbowNickname
version: 1.1.0
api-version: '1.21'
main: com.Lino.rainbowNickname.RainbowNickname
author: YourName
description: Plugin che aggiunge nickname animati con effetto arcobaleno

permissions:
  rainbownick.use:
    description: Permesso per avere il nickname animato arcobaleno
    default: op