name: RainbowNickname
version: 1.5
api-version: '1.21'
main: com.Lino.rainbowNickname.RainbowNickname
author: Lino
description: Plugin che aggiunge nickname animati con effetto arcobaleno

permissions:
  rainbownick.use:
    description: Permission to have animated rainbow nickname
    default: op
  rainbownick.admin:
    description: Permission to manage the plugin
    default: op
    children:
      rainbownick.use: true